spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/${KEYCLOAK_REALM:first-microService}/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/auth/realms/${KEYCLOAK_REALM:first-microService}
